### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/ecojob_analysis#1]
Duke job info
- [x] add locations from geo lookups
- [x] encode date into YYYY-MM-DD instead of MM/DD/YY 

Ecolog jobs
- [ ] Use duke jobs to identify job adds here
- [ ] identify volunteer ads as well
